In [1]:
import pandas as pd
import numpy as np
import os

In [2]:
id = '796768437'
id_token = 'ZMaefRB4oUfPcOx892VsAlWuU5sIYlGWXEiw7DVYt0AXDVUsPBSjsIegFol0EBIm0hKz2NWv7I1WKofhysQlWMoXGWHcJ6z6GJlKhcKXD5FqQ537Bvz0A7Bq3wvAOwHN'

In [3]:
import requests
import pandas as pd
import json

# Replace 'YOUR_SECRET_TOKEN' with your actual secret token
secret_token = 'YOUR_SECRET_TOKEN'
count = 10000 # Change this to the number of instances you want to retrieve
url = f"https://instances.social/api/1.0/instances/list?count={count}"

# Create headers with the Authorization header
headers = {
    'Authorization': f'Bearer {id_token}'
}

try:
    response = requests.get(url, headers=headers)

    if response.status_code == 200:
        response_data = response.content.decode('utf-8')  # Decode the bytes response to a string
        data = json.loads(response_data)  # Parse the JSON data as a list
        print(data)
        # Extract relevant information from the response and create a list of dictionaries
        instance_data = []
        instances = data.get('instances')
        for instance in instances:
          id = instance.get('id')
          name = instance.get('name')
          dead = instance.get('dead')
          user_count = instance.get('users')
          description = instance.get('info').get('full_description')
          short_description = instance.get('info').get('short_description')
          topic =  instance.get('info').get('topic')
          active_users = instance.get('info').get('active_users')

          instance_data.append({
                "Instance Id": id,
                "Instance Name": name,
                "Is Dead": dead,
                "User Count": user_count,
                "Description": description,
                "Short": short_description,
                "topic": topic,
                "active users": active_users
            })

        # Create a DataFrame from the list of dictionaries
        df = pd.DataFrame(instance_data)


        # Print the DataFrame
        print(df)
    else:
        print(f"Error: {response.status_code}")
except Exception as e:
    print(f"Error: {e}")

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)

In [4]:
df.to_csv('Instances_10000.csv')

In [5]:
df.head()

,Instance Id,Instance Name,Is Dead,User Count,Description,Short,topic,active users
0,58e10e8d72782604c488bd35,mastodon.xyz,False,28533,"<p>Follow <em>@status</em> for status updates,...","A Mastodon instance, open to everyone, but mai...",Mastodon,None
1,58e113f311c1a56b775b3933,awoo.space,False,1728,Awoo.space is a Mastodon instance where member...,Awoo.space is a Mastodon instance where member...,Awoo Space,None
2,58e11571a0edbc7317b4f531,social.tchncs.de,False,21208,"<p><a href=""https://status.tchncs.de"" target=_...",A friendly server from Germany – which tends t...,Mastodon,None
3,58e1157fa0edbc7317b4f532,animalliberation.social,False,1282,Animal Liberation Network is a community for <...,None,Animal Liberation Network,None
4,58e11af3831c8311929844aa,icosahedron.website,False,878,<h2>Site rules</h2>\n\n<p>In order for this we...,Icosahedron.website is a mastodon instance and...,Icosahedron,None

In [6]:
user_counts = list(df['User Count'])

In [8]:
min_users = min(user_counts)
max_users = max(user_counts)

In [9]:
print(min_users, max_users)

0 99884

In [12]:
df['User Count'] = df['User Count'].astype('int')

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Instance Id    10000 non-null  object
 1   Instance Name  10000 non-null  object
 2   Is Dead        10000 non-null  bool
 3   User Count     10000 non-null  int64
 4   Description    5877 non-null   object
 5   Short          6250 non-null   object
 6   topic          9989 non-null   object
 7   active users   0 non-null      object
dtypes: bool(1), int64(1), object(6)
memory usage: 556.8+ KB

In [16]:

# Filter instances with more than 1000 users
filtered_df = df[df['User Count'] > 2500]

In [17]:
filtered_df

,Instance Id,Instance Name,Is Dead,User Count,Description,Short,topic,active users
0,58e10e8d72782604c488bd35,mastodon.xyz,False,28533,"<p>Follow <em>@status</em> for status updates,...","A Mastodon instance, open to everyone, but mai...",Mastodon,None
2,58e11571a0edbc7317b4f531,social.tchncs.de,False,21208,"<p><a href=""https://status.tchncs.de"" target=_...",A friendly server from Germany – which tends t...,Mastodon,None
5,58e11ba6831c8311929844ab,hostux.social,False,8211,<p>This service is offered by alarig and valer...,European mastodon instance hosted in Luxembour...,Mastodon Hostux,None
14,58e277ff3f67c310eab28cb6,oc.todon.fr,False,2797,oc.todon.fr is a mostly French-speaking Mastod...,oc.todon.fr is a mostly French-speaking Mastod...,Octodon,None
17,58e2a6b69c99175decef88c7,octodon.social,False,12223,"<p><h2><a href=""https://en.wikipedia.org/wiki/...",queer anarchist communist cyber pirate ship,the Octodon,None
...,...,...,...,...,...,...,...,...
8635,63805bff2bae991d5f71fb3d,kitsunes.club,False,316036,"Welcome to KitsuClub, a Multipurpose community...","Welcome to KitsuClub, a Multipurpose community...",KitsuClub,None
8735,63819b243d42fc1c6cef55e0,dalliance.social,False,16409,An acitvitypub server for the dalliance networ...,An acitvitypub server for the dalliance networ...,Dalliance Social,None
9153,6387ec68b3a14f89149eaea6,stranger.social,False,8381,<p>Stranger.social is a general use server and...,"Welcome to Stranger Social, where strangers be...",stranger.social,None
9471,638e8ce9cee6fde70d06273b,loforo.com,False,35967,<h2 id='About'>About Loforo</h2>\n\n<p>Loforo ...,"Loforo.com is a fast, friendly and free microb...",loforo.com,None
9832,639cbbac89d02b725a623b93,bark.lgbt,False,4950,<h1>LGBTQ+ friendly furry instance</h1>\n\n<p>...,Furry focused instance for critters that like ...,Bark!,None

In [31]:
import random
final_list = []
# Check if there are at least 10 instances with more than 1000 users
if len(filtered_df) < 10:
    print("Not enough instances with more than 1000 users.")
else:
    # Randomly select 10 instances from the filtered DataFrame
    random_instances = filtered_df.sample(n=10)

    # Print the randomly selected instances with all details
    print("Randomly selected instances with more than 1000 users:")
print(random_instances)

Randomly selected instances with more than 1000 users:
                   Instance Id    Instance Name  Is Dead  User Count  \
949   5debf51bf075d202acccce9d      sfba.social    False       38547
876   5c4a0404049d8c7e85db33c2  dresden.network    False        3665
499   5a9089e30273bf1b12f09808    gensokyo.town    False        4501
6276  637b31bed94dca7f11e7bd41      pixelfed.de    False       27550
1985  637b1c50baf9cf97b71f2fd1        pxlmo.com    False        7050
1634  637820ef057570bcb618ba3b   stop.voring.me    False      649657
468   5a61153446fe0471227f118a   donphan.social    False        3334
1473  636e921580bb3f03b435a4bf      mastodon.ie    False       20669
978   5ef09cbd1bba02004a39debb        alive.bar    False       30118
387   59f3c095fe93291dbea8110c      muenster.im    False        4301

                                            Description  \
949   <h1 id="Welcome">Welcome to SFBA.social!</h1>\...
876   <h2>Impressum</h2>\n\n<h3>Angaben gemäß § 5 TM...
499   <h1 id="Terms of Use">利用規約</h1>\n\n<p>この利用規約（以...
6276  Pixelfed is an image sharing platform, an ethi...
1985  Pxlmo is an image sharing platform, an ethical...
1634  Fun and cozy hangout for furries and normies a...
468   <h2><img alt="Welcome to donphan.social!" src=...
1473  <p>A server started by people connected to Ire...
978   你好，欢迎使用 <a href="https://alive.bar">alive.bar<...
387   <h1>muenster.im</h1>\n\n<p>Dieser Mastodon Ser...

                                                  Short                topic  \
949   A Mastodon instance for the San Francisco Bay ...          SFBA.social
876   Dresden.Network ist eine Mastodon Instanz für ...      Dresden.Network
499   東方Projectが好きな人達が集まるマストドンサーバーです。This is a masto...        gensokyo.town
6276                       A welcoming instance for all          pixelfed.de
1985  Pxlmo is an image sharing platform, an ethical...                Pxlmo
1634  Fun and cozy hangout for furries and normies a...  ThoseFewCalculators
468   This generalist Mastodon server welcomes enthu...       donphan.social
1473  Irish Mastodon - run from Ireland, we welcome ...          mastodon.ie
978   你好，欢迎使用 alive.bar 社交媒体实例。\r\nalive.bar 仅仅是一个服务...            alive.bar
387   Aus Münster für Münster und für alle anderen n...          muenster.im

     active users
949          None
876          None
499          None
6276         None
1985         None
1634         None
468          None
1473         None
978          None
387          None

In [32]:
final_df = pd.DataFrame(random_instances)

In [33]:
final_df

,Instance Id,Instance Name,Is Dead,User Count,Description,Short,topic,active users
949,5debf51bf075d202acccce9d,sfba.social,False,38547,"<h1 id=""Welcome"">Welcome to SFBA.social!</h1>\...",A Mastodon instance for the San Francisco Bay ...,SFBA.social,None
876,5c4a0404049d8c7e85db33c2,dresden.network,False,3665,<h2>Impressum</h2>\n\n<h3>Angaben gemäß § 5 TM...,Dresden.Network ist eine Mastodon Instanz für ...,Dresden.Network,None
499,5a9089e30273bf1b12f09808,gensokyo.town,False,4501,"<h1 id=""Terms of Use"">利用規約</h1>\n\n<p>この利用規約（以...",東方Projectが好きな人達が集まるマストドンサーバーです。This is a masto...,gensokyo.town,None
6276,637b31bed94dca7f11e7bd41,pixelfed.de,False,27550,"Pixelfed is an image sharing platform, an ethi...",A welcoming instance for all,pixelfed.de,None
1985,637b1c50baf9cf97b71f2fd1,pxlmo.com,False,7050,"Pxlmo is an image sharing platform, an ethical...","Pxlmo is an image sharing platform, an ethical...",Pxlmo,None
1634,637820ef057570bcb618ba3b,stop.voring.me,False,649657,Fun and cozy hangout for furries and normies a...,Fun and cozy hangout for furries and normies a...,ThoseFewCalculators,None
468,5a61153446fe0471227f118a,donphan.social,False,3334,"<h2><img alt=""Welcome to donphan.social!"" src=...",This generalist Mastodon server welcomes enthu...,donphan.social,None
1473,636e921580bb3f03b435a4bf,mastodon.ie,False,20669,<p>A server started by people connected to Ire...,"Irish Mastodon - run from Ireland, we welcome ...",mastodon.ie,None
978,5ef09cbd1bba02004a39debb,alive.bar,False,30118,"你好，欢迎使用 <a href=""https://alive.bar"">alive.bar<...",你好，欢迎使用 alive.bar 社交媒体实例。\r\nalive.bar 仅仅是一个服务...,alive.bar,None
387,59f3c095fe93291dbea8110c,muenster.im,False,4301,<h1>muenster.im</h1>\n\n<p>Dieser Mastodon Ser...,Aus Münster für Münster und für alle anderen n...,muenster.im,None

In [35]:
final_df.to_csv('Final_Instances1.csv')

In [30]:
names = final_df['Instance Name']
print(names)

38              mstdn.fr
1606      genomic.social
5296      mastodon.green
804      mastodontech.de
4435         fgc.network
409          ruhr.social
996     kolektiva.social
6210     bookwyrm.social
1108          pol.social
273       scholar.social
Name: Instance Name, dtype: object

In [46]:
df1 = pd.read_csv('Final_Instances.csv')

In [47]:
df1

,Unnamed: 0,Instance Id,Instance Name,Is Dead,User Count,Description,Short,topic,active users
0,38,58e50f85e6c0eb779279822c,mstdn.fr,False,2512,<p>[FR]</p>\n\n<p>L'accès est ouvert à tou⋅te⋅...,NaN,mstdn,NaN
1,1606,6377213780bb3f03b435a689,genomic.social,False,3631,<h2>About</h2>\n\n<p>A Mastodon server for the...,A Mastodon server for the Genomic Science Comm...,genomic.social,NaN
2,5296,637b2fc3d94dca7f11e7b564,mastodon.green,False,11910,"<h2 id=""about-mastodon-green"">Mastodon.green</...",Plant trees while you use Mastodon. A server o...,Mastodon.green,NaN
3,804,5b8f9c0436205a4e89370d09,mastodontech.de,False,16530,<h2>Impressum</h2>\n\n<h3>Angaben gemäß § 5 TM...,Offen für alle (über 16) und bereitgestellt vo...,MastodonTech.de,NaN
4,4435,637b2dc1d94dca7f11e7ad4d,fgc.network,False,3862,The Fighting Game Community on the fediverse.,NaN,FGC.Network,NaN
5,409,5a3be5a567eb6930d0cf7400,ruhr.social,False,10383,<h2>Willkommen!</h2>\n\n<p>Herzlich willkommen...,NaN,ruhr.social,NaN
6,996,5f4951e41bba02004a39df91,kolektiva.social,False,36848,<h1>CONTACT US</h1>\n\n<p>Feel free to message...,Kolektiva is an anti-colonial anarchist collec...,kolektiva.social,NaN
7,6210,637b319fd94dca7f11e7bcd2,bookwyrm.social,False,14138,"<p class=""title is-5"">Talk about books, track ...",BookWyrm's flagship instance: Talk about books...,BookWyrm,NaN
8,1108,61a73929482824006ec0ff45,pol.social,False,6725,<p>Serwer Fediwersum prowadzony jest przez <a ...,Serwer głównie dla użytkowników polskojęzycznych.,Pol.social,NaN
9,273,5902589f0c4b3c46f854d273,scholar.social,False,4793,<h1>Scholar Social Community Standards</h1>\n\...,"Microblogging for researchers, grad students, ...",Scholar Social,NaN

In [49]:
df1 = df1.iloc[:-1]
df1

,Unnamed: 0,Instance Id,Instance Name,Is Dead,User Count,Description,Short,topic,active users
0,38,58e50f85e6c0eb779279822c,mstdn.fr,False,2512,<p>[FR]</p>\n\n<p>L'accès est ouvert à tou⋅te⋅...,NaN,mstdn,NaN
1,1606,6377213780bb3f03b435a689,genomic.social,False,3631,<h2>About</h2>\n\n<p>A Mastodon server for the...,A Mastodon server for the Genomic Science Comm...,genomic.social,NaN
2,5296,637b2fc3d94dca7f11e7b564,mastodon.green,False,11910,"<h2 id=""about-mastodon-green"">Mastodon.green</...",Plant trees while you use Mastodon. A server o...,Mastodon.green,NaN
3,804,5b8f9c0436205a4e89370d09,mastodontech.de,False,16530,<h2>Impressum</h2>\n\n<h3>Angaben gemäß § 5 TM...,Offen für alle (über 16) und bereitgestellt vo...,MastodonTech.de,NaN
4,4435,637b2dc1d94dca7f11e7ad4d,fgc.network,False,3862,The Fighting Game Community on the fediverse.,NaN,FGC.Network,NaN
5,409,5a3be5a567eb6930d0cf7400,ruhr.social,False,10383,<h2>Willkommen!</h2>\n\n<p>Herzlich willkommen...,NaN,ruhr.social,NaN
6,996,5f4951e41bba02004a39df91,kolektiva.social,False,36848,<h1>CONTACT US</h1>\n\n<p>Feel free to message...,Kolektiva is an anti-colonial anarchist collec...,kolektiva.social,NaN
7,6210,637b319fd94dca7f11e7bcd2,bookwyrm.social,False,14138,"<p class=""title is-5"">Talk about books, track ...",BookWyrm's flagship instance: Talk about books...,BookWyrm,NaN

In [41]:
rows_to_insert = final_df.iloc[[0, 3]]
rows_to_insert

,Instance Id,Instance Name,Is Dead,User Count,Description,Short,topic,active users
949,5debf51bf075d202acccce9d,sfba.social,False,38547,"<h1 id=""Welcome"">Welcome to SFBA.social!</h1>\...",A Mastodon instance for the San Francisco Bay ...,SFBA.social,None
6276,637b31bed94dca7f11e7bd41,pixelfed.de,False,27550,"Pixelfed is an image sharing platform, an ethi...",A welcoming instance for all,pixelfed.de,None

In [50]:
result_df = pd.concat([df1, rows_to_insert], ignore_index=True)
result_df

,Unnamed: 0,Instance Id,Instance Name,Is Dead,User Count,Description,Short,topic,active users
0,38.0,58e50f85e6c0eb779279822c,mstdn.fr,False,2512,<p>[FR]</p>\n\n<p>L'accès est ouvert à tou⋅te⋅...,NaN,mstdn,NaN
1,1606.0,6377213780bb3f03b435a689,genomic.social,False,3631,<h2>About</h2>\n\n<p>A Mastodon server for the...,A Mastodon server for the Genomic Science Comm...,genomic.social,NaN
2,5296.0,637b2fc3d94dca7f11e7b564,mastodon.green,False,11910,"<h2 id=""about-mastodon-green"">Mastodon.green</...",Plant trees while you use Mastodon. A server o...,Mastodon.green,NaN
3,804.0,5b8f9c0436205a4e89370d09,mastodontech.de,False,16530,<h2>Impressum</h2>\n\n<h3>Angaben gemäß § 5 TM...,Offen für alle (über 16) und bereitgestellt vo...,MastodonTech.de,NaN
4,4435.0,637b2dc1d94dca7f11e7ad4d,fgc.network,False,3862,The Fighting Game Community on the fediverse.,NaN,FGC.Network,NaN
5,409.0,5a3be5a567eb6930d0cf7400,ruhr.social,False,10383,<h2>Willkommen!</h2>\n\n<p>Herzlich willkommen...,NaN,ruhr.social,NaN
6,996.0,5f4951e41bba02004a39df91,kolektiva.social,False,36848,<h1>CONTACT US</h1>\n\n<p>Feel free to message...,Kolektiva is an anti-colonial anarchist collec...,kolektiva.social,NaN
7,6210.0,637b319fd94dca7f11e7bcd2,bookwyrm.social,False,14138,"<p class=""title is-5"">Talk about books, track ...",BookWyrm's flagship instance: Talk about books...,BookWyrm,NaN
8,NaN,5debf51bf075d202acccce9d,sfba.social,False,38547,"<h1 id=""Welcome"">Welcome to SFBA.social!</h1>\...",A Mastodon instance for the San Francisco Bay ...,SFBA.social,None
9,NaN,637b31bed94dca7f11e7bd41,pixelfed.de,False,27550,"Pixelfed is an image sharing platform, an ethi...",A welcoming instance for all,pixelfed.de,None

In [51]:
result_df.to_csv('Final_Instance_list.csv')

In [52]:
names = result_df['Instance Name']
print(names)

0            mstdn.fr
1      genomic.social
2      mastodon.green
3     mastodontech.de
4         fgc.network
5         ruhr.social
6    kolektiva.social
7     bookwyrm.social
8         sfba.social
9         pixelfed.de
Name: Instance Name, dtype: object